<a href="https://colab.research.google.com/github/Abubakar-Siddiq254/Abubakar-Siddiq254/blob/main/MDS_LAB_INTERNAL_J8_23.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [31]:
import pandas as pd
import numpy as np




s1 = pd.Series([10, 20, 30, 40], name="MyList")
print("From List:\n", s1, "\n")


s2 = pd.Series({'a': 100, 'b': 200, 'c': 300})
print("From Dictionary:\n", s2, "\n")


s3 = pd.Series(np.random.randn(3), index=['x', 'y', 'z'])
print("From NumPy Array:\n", s3, "\n")

print("=== PANDAS DATAFRAMES ===")

df1 = pd.DataFrame({
    'A': [1, 2, 3],
    'B': ['X', 'Y', 'Z']
})
print("From Dict of Lists:\n")
display(df1)

df2 = pd.DataFrame([
    {'Name': 'Alice', 'Age': 25},
    {'Name': 'Bob', 'Age': 30}
])
print("\nFrom List of Dicts:\n")
display(df2)

df3 = pd.DataFrame(
    np.random.randint(10, 50, size=(3, 3)),
    columns=['Col_1', 'Col_2', 'Col_3'],
    index=['Row_A', 'Row_B', 'Row_C']
)
print("\nFrom 2D NumPy Array:\n")
display(df3)

From List:
 0    10
1    20
2    30
3    40
Name: MyList, dtype: int64

From Dictionary:
 a    100
b    200
c    300
dtype: int64

From NumPy Array:
 x    0.089394
y   -0.119851
z    0.113729
dtype: float64

=== PANDAS DATAFRAMES ===
From Dict of Lists:

   A  B
0  1  X
1  2  Y
2  3  Z

From List of Dicts:

    Name  Age
0  Alice   25
1    Bob   30

From 2D NumPy Array:

       Col_1  Col_2  Col_3
Row_A     46     23     39
Row_B     44     30     46
Row_C     14     28     23